version: '3'
services:
  server:
    build:
      dockerfile: ./Dockerfile
      context: .
    command: yarn dev
    volumes:
      - .:/home/node
      - ./node_modules:/home/node/node_modules
    stdin_open: true
    tty: true
    ports:
      - "3001:3001"
    depends_on:
      - db
    
      db:
        image: mysql:5.7
        restart: always
        environment:
          MYSQL_DATABASE: 'db'
          MYSQL_USER: 'user'
          MYSQL_PASSWORD: 'password'
          MYSQL_ROOT_PASSWORD: 'password'
        ports:
          - '${DATABASE_PORT}:5432'
        volumes:
          - ustore_challenge_db:/var/lib/mysql
    volumes:
      ustore_challenge_db: