version: '3'
services:
  server:
    build:
      dockerfile: ./Dockerfile
      context: .
    command: yarn dev
    volumes:
      - .:/home/node
      - ./node_modules:/home/node/node_modules
    stdin_open: true
    tty: true
    ports:
      - "3001:3001"
    depends_on:
      - db
    
      db:
        image: mysql:5.7
        restart: always
        environment:
          POSTGRES_USER: ${DATABASE_USER}
          POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
          POSTGRES_DB: ${DATABASE_DB}
        ports:
          - '${DATABASE_PORT}:5432'
        volumes:
          - ustore_challenge_db:/var/lib/mysql
    volumes:
      ustore_challenge_db: