version: '3'
services:
  server:
    build:
      dockerfile: ./Dockerfile
      context: .
    command: yarn dev
    volumes:
      - .:/home/node
      - ./node_modules:/home/node/node_modules
    stdin_open: true
    tty: true
    ports:
      - "3001:3001"
    depends_on:
      - db
    
  db:
    container_name: ${DATABASE_NAME}-db
    image: mysql:5.7
    restart: always
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DB: ${DATABASE_DB}
      MYSQL_ROOT_PASSWORD: mysqlrootpassword@123@
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - ustoredb:/var/lib/mysql
volumes:
  ustoredb: